/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/constants/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-on-surface": "#2c3135",
        "on-tertiary": "#472a00",
        "on-background": "#dee3e8",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#38485d",
        "surface": "#0f1418",
        "primary-fixed": "#c4e7ff",
        "on-surface": "#dee3e8",
        "secondary-container": "#3a4a5f",
        "surface-container-lowest": "#0a0f12",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-highest": "#303539",
        "surface-bright": "#343a3e",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-container": "#f1a02b",
        "secondary-fixed-dim": "#b7c8e1",
        "on-error": "#690005",
        "outline": "#87929a",
        "secondary": "#b7c8e1",
        "surface-dim": "#0f1418",
        "outline-variant": "#3e484f",
        "background": "#0f1418",
        "inverse-primary": "#00668a",
        "on-primary-fixed": "#001e2c",
        "tertiary": "#ffc176",
        "error-container": "#93000a",
        "surface-container": "#1b2024",
        "on-primary-fixed-variant": "#004c69",
        "on-primary": "#00354a",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary": "#213145",
        "on-tertiary-container": "#613b00",
        "surface-variant": "#303539",
        "primary": "#8ed5ff",
        "surface-container-high": "#252b2e",
        "surface-container-low": "#171c20",
        "on-surface-variant": "#bdc8d1",
        "inverse-surface": "#dee3e8",
        "secondary-fixed": "#d3e4fe",
        "tertiary-fixed-dim": "#ffb960",
        "on-primary-container": "#004965",
        "surface-tint": "#7bd0ff",
        "primary-container": "#38bdf8",
        "primary-fixed-dim": "#7bd0ff",
        "on-secondary-container": "#a9bad3",
        "semantic-bullish": "#4ade80", 
        "semantic-bearish": "#f87171" 
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-padding": "24px",
        "section-margin": "32px",
        "unit": "4px",
        "gutter": "16px",
        "component-gap-md": "12px",
        "component-gap-sm": "8px"
      },
      "fontFamily": {
        "heading-table": ["Inter", "sans-serif"],
        "data-mono": ["Geist Mono", "monospace"],
        "ticker-lg": ["Geist Mono", "monospace"],
        "display-sm": ["Inter", "sans-serif"],
        "body-standard": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "heading-table": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "data-mono": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "ticker-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-sm": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-standard": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
