#:schema node_modules/wrangler/config-schema.json
name = "liquidity-research-frontend"
compatibility_date = "2024-05-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_API_URL = "https://quant.indonesiastockanalyst.my.id"
