"""
DBX Index Constituents — All Indonesian Stocks (Second Liners)
"""

DBX_TICKERS: list[dict] = [
    {'ticker': 'ACRO.JK', 'name': 'Samcro Hyosung Adilestari', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ACST.JK', 'name': 'Acset Indonusa', 'sector': 'Infrastruktur'},
    {'ticker': 'ADCP.JK', 'name': 'Adhi Commuter Properti', 'sector': 'Properti & Real Estat'},
    {'ticker': 'ADES.JK', 'name': 'Akasha Wira International', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'ADMF.JK', 'name': 'Adira Dinamika Multi Finance', 'sector': 'Keuangan'},
    {'ticker': 'ADMG.JK', 'name': 'Polychem Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'AGAR.JK', 'name': 'Asia Sejahtera Mina', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'AGII.JK', 'name': 'Samator Indo Gas', 'sector': 'Barang Baku'},
    {'ticker': 'AGRS.JK', 'name': 'Bank IBK Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'AHAP.JK', 'name': 'Asuransi Harta Aman Pratama', 'sector': 'Keuangan'},
    {'ticker': 'AIMS.JK', 'name': 'Artha Mahiya Investama', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'AKPI.JK', 'name': 'Argha Karya Prima Ind.', 'sector': 'Barang Baku'},
    {'ticker': 'AKSI.JK', 'name': 'Mineral Sumberdaya Mandiri', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'ALDO.JK', 'name': 'Alkindo Naratama', 'sector': 'Barang Baku'},
    {'ticker': 'ALKA.JK', 'name': 'Alakasa Industrindo', 'sector': 'Barang Baku'},
    {'ticker': 'ALMI.JK', 'name': 'Alumindo Light Metal Industry', 'sector': 'Barang Baku'},
    {'ticker': 'AMAG.JK', 'name': 'Asuransi Multi Artha Guna', 'sector': 'Keuangan'},
    {'ticker': 'AMAN.JK', 'name': 'Makmur Berkah Amanda', 'sector': 'Properti & Real Estat'},
    {'ticker': 'AMAR.JK', 'name': 'Bank Amar Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'AMFG.JK', 'name': 'Asahimas Flat Glass', 'sector': 'Barang Baku'},
    {'ticker': 'AMIN.JK', 'name': "Ateliers Mecaniques D'Indonesie", 'sector': 'Perindustrian'},
    {'ticker': 'AMOR.JK', 'name': 'Ashmore Asset Management Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'ANJT.JK', 'name': 'Austindo Nusantara Jaya', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'APEX.JK', 'name': 'Apexindo Pratama Duta', 'sector': 'Energi'},
    {'ticker': 'APIC.JK', 'name': 'Pacific Strategic Financial', 'sector': 'Keuangan'},
    {'ticker': 'APII.JK', 'name': 'Arita Prima Indonesia', 'sector': 'Perindustrian'},
    {'ticker': 'APLI.JK', 'name': 'Asiaplast Industries', 'sector': 'Barang Baku'},
    {'ticker': 'ARCI.JK', 'name': 'Archi Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'AREA.JK', 'name': 'Arkadia Digital Media', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ARGO.JK', 'name': 'Argo Pantes', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ARII.JK', 'name': 'Atlas Resources', 'sector': 'Energi'},
    {'ticker': 'ARKO.JK', 'name': 'Arkora Hydro', 'sector': 'Infrastruktur'},
    {'ticker': 'ARTA.JK', 'name': 'Arthavest', 'sector': 'Keuangan'},
    {'ticker': 'ARTO.JK', 'name': 'Bank Jago', 'sector': 'Keuangan'},
    {'ticker': 'ASBI.JK', 'name': 'Asuransi Bintang', 'sector': 'Keuangan'},
    {'ticker': 'ASDM.JK', 'name': 'Asuransi Dayin Mitra', 'sector': 'Keuangan'},
    {'ticker': 'ASHA.JK', 'name': 'Cilacap Samudera Fishing Industry', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'ASJT.JK', 'name': 'Asuransi Jasa Tania', 'sector': 'Keuangan'},
    {'ticker': 'ASLC.JK', 'name': 'Autopedia Sukses Lestari', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ASLI.JK', 'name': 'Asli Rancangan Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'ASPI.JK', 'name': 'Andalan Sakti Primaindo', 'sector': 'Properti & Real Estat'},
    {'ticker': 'ASPR.JK', 'name': 'Aspira Hana Finance', 'sector': 'Keuangan'},
    {'ticker': 'ASRM.JK', 'name': 'Asuransi Ramayana', 'sector': 'Keuangan'},
    {'ticker': 'ATAP.JK', 'name': 'Trimitra Prawara Goldland', 'sector': 'Properti & Real Estat'},
    {'ticker': 'ATIC.JK', 'name': 'Anabatic Technologies', 'sector': 'Teknologi'},
    {'ticker': 'ATLA.JK', 'name': 'Atlantis Subsea Indonesia', 'sector': 'Energi'},
    {'ticker': 'AWAN.JK', 'name': 'Era Digital Media', 'sector': 'Teknologi'},
    {'ticker': 'AXIO.JK', 'name': 'Tera Data Indonusa', 'sector': 'Teknologi'},
    {'ticker': 'AYAM.JK', 'name': 'Jayamas Medica Industri', 'sector': 'Kesehatan'},
    {'ticker': 'AYLS.JK', 'name': 'Agro Yasa Lestari', 'sector': 'Barang Baku'},
    {'ticker': 'BABP.JK', 'name': 'Bank MNC Internasional', 'sector': 'Keuangan'},
    {'ticker': 'BABY.JK', 'name': 'Multitrend Indo', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BAIK.JK', 'name': 'Bank Artha Graha Internasional', 'sector': 'Keuangan'},
    {'ticker': 'BAJA.JK', 'name': 'Saranacentral Bajatama', 'sector': 'Barang Baku'},
    {'ticker': 'BANK.JK', 'name': 'Bank Aladin Syariah', 'sector': 'Keuangan'},
    {'ticker': 'BAPA.JK', 'name': 'Bekasi Asri Pemula', 'sector': 'Properti & Real Estat'},
    {'ticker': 'BATR.JK', 'name': 'Batulicin Nusantara Maritim', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BBKP.JK', 'name': 'Bank KB Bukopin', 'sector': 'Keuangan'},
    {'ticker': 'BBLD.JK', 'name': 'Buana Finance', 'sector': 'Keuangan'},
    {'ticker': 'BBMD.JK', 'name': 'Bank Mestika Dharma', 'sector': 'Keuangan'},
    {'ticker': 'BBRM.JK', 'name': 'Pelayaran Nasional Bina Buana Raya', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BBSS.JK', 'name': 'Bumi Benowo Sukses Sejahtera', 'sector': 'Properti & Real Estat'},
    {'ticker': 'BCIC.JK', 'name': 'Bank JTrust Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'BCIP.JK', 'name': 'Bumi Citra Permai', 'sector': 'Properti & Real Estat'},
    {'ticker': 'BEEF.JK', 'name': 'Estika Tata Tiara', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'BEER.JK', 'name': 'Jobubu Jarum Minahasa', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'BELL.JK', 'name': 'Trisula Textile Industries', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BESS.JK', 'name': 'Batulicin Nusantara Maritim', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BHAT.JK', 'name': 'Bhakti Multi Artha', 'sector': 'Keuangan'},
    {'ticker': 'BIKE.JK', 'name': 'Sepeda Bersama Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BINO.JK', 'name': 'Perma Plasindo', 'sector': 'Perindustrian'},
    {'ticker': 'BIPI.JK', 'name': 'Astrindo Nusantara Infrastruktur', 'sector': 'Energi'},
    {'ticker': 'BKSW.JK', 'name': 'Bank QNB Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'BLES.JK', 'name': 'Superior Prima Sukses', 'sector': 'Barang Baku'},
    {'ticker': 'BLUE.JK', 'name': 'Berkah Prima Perkasa', 'sector': 'Teknologi'},
    {'ticker': 'BMAS.JK', 'name': 'Bank Maspion Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'BMSR.JK', 'name': 'Bintang Mitra Semestaraya', 'sector': 'Barang Baku'},
    {'ticker': 'BNBA.JK', 'name': 'Bank Bumi Arta', 'sector': 'Keuangan'},
    {'ticker': 'BOAT.JK', 'name': 'Pelayaran Kurnia Lautan Semesta', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BOBA.JK', 'name': 'Formosa Ingredient Factory', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'BOGA.JK', 'name': 'Bintang Oto Global', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BOLT.JK', 'name': 'Garuda Metalindo', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BPFI.JK', 'name': 'Batavia Prosperindo Finance', 'sector': 'Keuangan'},
    {'ticker': 'BPII.JK', 'name': 'Batavia Prosperindo Internasional', 'sector': 'Keuangan'},
    {'ticker': 'BPTR.JK', 'name': 'Batavia Prosperindo Trans', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BRAM.JK', 'name': 'Indo Kordsa', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'BRNA.JK', 'name': 'Berlina', 'sector': 'Barang Baku'},
    {'ticker': 'BRRC.JK', 'name': 'Barito Renewables Energy', 'sector': 'Infrastruktur'},
    {'ticker': 'BSBK.JK', 'name': 'Wulandari Bangun Laksana', 'sector': 'Properti & Real Estat'},
    {'ticker': 'BSML.JK', 'name': 'Bintang Samudera Mandiri Lines', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BSSR.JK', 'name': 'Baramulti Suksessarana', 'sector': 'Energi'},
    {'ticker': 'BTON.JK', 'name': 'Betonjaya Manunggal', 'sector': 'Barang Baku'},
    {'ticker': 'BUAH.JK', 'name': 'Segar Kumala Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'BULL.JK', 'name': 'Buana Laju Leyland', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'BUVA.JK', 'name': 'Bukit Uluwatu Villa', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CAKK.JK', 'name': 'Cahayaputra Asa Keramik', 'sector': 'Barang Baku'},
    {'ticker': 'CAMP.JK', 'name': 'Campina Ice Cream Industry', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'CARE.JK', 'name': 'Metro Healthcare Indonesia', 'sector': 'Kesehatan'},
    {'ticker': 'CASA.JK', 'name': 'Capital Financial Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'CBPE.JK', 'name': 'Citra Buana Prasida', 'sector': 'Properti & Real Estat'},
    {'ticker': 'CBRE.JK', 'name': 'Cakra Buana Resources Energi', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'CBUT.JK', 'name': 'Citra Borneo Utama', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'CCSI.JK', 'name': 'Communication Cable Systems Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'CDIA.JK', 'name': 'Ciputra Development', 'sector': 'Properti & Real Estat'},
    {'ticker': 'CEKA.JK', 'name': 'Wilmar Cahaya Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'CENT.JK', 'name': 'Centratama Telekomunikasi Indonesia', 'sector': 'Infrastruktur'},
    {'ticker': 'CGAS.JK', 'name': 'Citra Nusantara Gemilang', 'sector': 'Energi'},
    {'ticker': 'CHEK.JK', 'name': 'Champ Resto Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CHEM.JK', 'name': 'Chemstar Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'CINT.JK', 'name': 'Chitose Internasional', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CITY.JK', 'name': 'Natura City Developments', 'sector': 'Properti & Real Estat'},
    {'ticker': 'CLAY.JK', 'name': 'Citra Putra Realty', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CLPI.JK', 'name': 'Colorpak Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'CMNT.JK', 'name': 'Cemindo Gemilang', 'sector': 'Barang Baku'},
    {'ticker': 'CNMA.JK', 'name': 'Nusantara Sejahtera Raya', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'COAL.JK', 'name': 'Black Diamond Resources', 'sector': 'Energi'},
    {'ticker': 'COIN.JK', 'name': 'Canggu Internasional', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CPRO.JK', 'name': 'Central Proteina Prima', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'CRAB.JK', 'name': 'Toba Surimi Industries', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'CRSN.JK', 'name': 'Carsurin', 'sector': 'Perindustrian'},
    {'ticker': 'CSAP.JK', 'name': 'Catur Sentosa Adiprana', 'sector': 'Perindustrian'},
    {'ticker': 'CSIS.JK', 'name': 'Cahayasakti Investindo', 'sector': 'Perindustrian'},
    {'ticker': 'CSMI.JK', 'name': 'Cipta Selera Murni', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'CTBN.JK', 'name': 'Citra Tubindo', 'sector': 'Energi'},
    {'ticker': 'CTTH.JK', 'name': 'Citatah', 'sector': 'Barang Baku'},
    {'ticker': 'CYBR.JK', 'name': 'Cybernet Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'DADA.JK', 'name': 'Diamond Citra Propertindo', 'sector': 'Properti & Real Estat'},
    {'ticker': 'DART.JK', 'name': 'Duta Anggada Realty', 'sector': 'Properti & Real Estat'},
    {'ticker': 'DATA.JK', 'name': 'DCI Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'DAYA.JK', 'name': 'Daya Mulia Turangga', 'sector': 'Energi'},
    {'ticker': 'DCII.JK', 'name': 'DCI Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'DEFI.JK', 'name': 'Duta Elok Persada', 'sector': 'Keuangan'},
    {'ticker': 'DEPO.JK', 'name': 'Caturkarda Depo Bangunan', 'sector': 'Perindustrian'},
    {'ticker': 'DEWI.JK', 'name': 'Dewi Shri Farmindo', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'DFAM.JK', 'name': 'Dafam Property Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'DGIK.JK', 'name': 'Nusa Konstruksi Enjiniring', 'sector': 'Infrastruktur'},
    {'ticker': 'DGNS.JK', 'name': 'Diagnos Laboratorium Utama', 'sector': 'Kesehatan'},
    {'ticker': 'DIVA.JK', 'name': 'Distribusi Voucher Nusantara', 'sector': 'Teknologi'},
    {'ticker': 'DKFT.JK', 'name': 'Central Omega Resources', 'sector': 'Barang Baku'},
    {'ticker': 'DKHH.JK', 'name': 'Duta Intidaya', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'DMMX.JK', 'name': 'Digital Mediatama Maxima', 'sector': 'Teknologi'},
    {'ticker': 'DMND.JK', 'name': 'Diamond Food Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'DNAR.JK', 'name': 'Bank Oke Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'DOOH.JK', 'name': 'Era Media Sejahtera', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'DOSS.JK', 'name': 'Global Digital Niaga', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'DPNS.JK', 'name': 'Duta Pertiwi Nusantara', 'sector': 'Barang Baku'},
    {'ticker': 'DPUM.JK', 'name': 'Dua Putra Utama Makmur', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'DSFI.JK', 'name': 'Dharma Samudera Fishing Industries', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'DUTI.JK', 'name': 'Duta Pertiwi', 'sector': 'Properti & Real Estat'},
    {'ticker': 'DVLA.JK', 'name': 'Darya-Varia Laboratoria', 'sector': 'Kesehatan'},
    {'ticker': 'DWGL.JK', 'name': 'Dwi Guna Laksana', 'sector': 'Energi'},
    {'ticker': 'DYAN.JK', 'name': 'Dyandra Media International', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'EAST.JK', 'name': 'Eastparc Hotel', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ECII.JK', 'name': 'Electronic City Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'EDGE.JK', 'name': 'Indointernet', 'sector': 'Teknologi'},
    {'ticker': 'EKAD.JK', 'name': 'Ekadharma International', 'sector': 'Barang Baku'},
    {'ticker': 'ELIT.JK', 'name': 'Data Sinergitama Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'EMAS.JK', 'name': 'Elang Mahkota Teknologi', 'sector': 'Teknologi'},
    {'ticker': 'EMDE.JK', 'name': 'Megapolitan Developments', 'sector': 'Properti & Real Estat'},
    {'ticker': 'ENAK.JK', 'name': 'Champ Resto Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'EPMT.JK', 'name': 'Enseval Putera Megatrading', 'sector': 'Kesehatan'},
    {'ticker': 'ERTX.JK', 'name': 'Eratex Djaja', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ESIP.JK', 'name': 'Sinergi Inti Plastindo', 'sector': 'Barang Baku'},
    {'ticker': 'ESTA.JK', 'name': 'Esta Multi Usaha', 'sector': 'Keuangan'},
    {'ticker': 'ESTI.JK', 'name': 'Ever Shine Tex', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FAPA.JK', 'name': 'FAP Agri', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'FAST.JK', 'name': 'Fast Food Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FIRE.JK', 'name': 'Alfa Energi Investama', 'sector': 'Energi'},
    {'ticker': 'FISH.JK', 'name': 'F昌 Samudera', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'FITT.JK', 'name': 'Fitra Food Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'FMII.JK', 'name': 'Fortune Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FOLK.JK', 'name': 'Multi Medika Internasional', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FORE.JK', 'name': 'Fore Kopi Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FORU.JK', 'name': 'Fortune Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'FPNI.JK', 'name': 'Lotte Chemical Titan', 'sector': 'Barang Baku'},
    {'ticker': 'FUJI.JK', 'name': 'Fuji Finance Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'FUTR.JK', 'name': 'Lini Imaji Kreasi Ekosistem', 'sector': 'Teknologi'},
    {'ticker': 'FWCT.JK', 'name': 'Wijaya Cahaya Timber', 'sector': 'Barang Baku'},
    {'ticker': 'GDST.JK', 'name': 'Gunawan Dianjaya Steel', 'sector': 'Barang Baku'},
    {'ticker': 'GDYR.JK', 'name': 'Goodyear Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'GEMA.JK', 'name': 'Gema Grahasarana', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'GGRP.JK', 'name': 'Gunung Raja Paksi', 'sector': 'Barang Baku'},
    {'ticker': 'GHON.JK', 'name': 'Global Teleshop', 'sector': 'Infrastruktur'},
    {'ticker': 'GLVA.JK', 'name': 'Galva Technologies', 'sector': 'Teknologi'},
    {'ticker': 'GMTD.JK', 'name': 'Gowa Makassar Tourism Dev.', 'sector': 'Properti & Real Estat'},
    {'ticker': 'GOLD.JK', 'name': 'Intra Golflink Resorts', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'GPRA.JK', 'name': 'Perdana Gapuraprima', 'sector': 'Properti & Real Estat'},
    {'ticker': 'GPSO.JK', 'name': 'Geoprima Solusi', 'sector': 'Teknologi'},
    {'ticker': 'GRIA.JK', 'name': 'Ingria Pratama Capitalindo', 'sector': 'Properti & Real Estat'},
    {'ticker': 'GRPH.JK', 'name': 'Graha Prima Mentari', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'GSMF.JK', 'name': 'Global Teleshop', 'sector': 'Keuangan'},
    {'ticker': 'GTBO.JK', 'name': 'Garda Tujuh Buana', 'sector': 'Energi'},
    {'ticker': 'GTRA.JK', 'name': 'Grahabelas Trisna', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'GULA.JK', 'name': 'Aman Agrindo', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'GUNA.JK', 'name': 'Guna Timur Raya', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'GZCO.JK', 'name': 'Gozco Plantations', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'HAIS.JK', 'name': 'Hasnur Internasional Shipping', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'HALO.JK', 'name': 'Haloni Jane', 'sector': 'Kesehatan'},
    {'ticker': 'HDFA.JK', 'name': 'Radana Bhaskara Finance', 'sector': 'Keuangan'},
    {'ticker': 'HDIT.JK', 'name': 'Hensel Davest Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'HELI.JK', 'name': 'Jaya Trishindo', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'HERO.JK', 'name': 'Hero Supermarket', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'HGII.JK', 'name': 'Hero Global Investment', 'sector': 'Keuangan'},
    {'ticker': 'HOKI.JK', 'name': 'Buyung Poetra Sembada', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'HOMI.JK', 'name': 'Grand House Mulia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'HOPE.JK', 'name': 'Harapan Duta Pertiwi', 'sector': 'Perindustrian'},
    {'ticker': 'HUMI.JK', 'name': 'Humpuss Maritim Internasional', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'HYGN.JK', 'name': 'Ecocare Indo Pasifik', 'sector': 'Perindustrian'},
    {'ticker': 'IATA.JK', 'name': 'MNC Energy Investments', 'sector': 'Energi'},
    {'ticker': 'IDPR.JK', 'name': 'Indonesia Kendaraan Terminal', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'IFII.JK', 'name': 'Indonesia Fibreboard Industry', 'sector': 'Barang Baku'},
    {'ticker': 'IFSH.JK', 'name': 'Itama Ranoraya', 'sector': 'Kesehatan'},
    {'ticker': 'IGAR.JK', 'name': 'Champion Pacific Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'IKAN.JK', 'name': 'Era Mandiri Cemerlang', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'IKBI.JK', 'name': 'Sumi Indo Kabel', 'sector': 'Perindustrian'},
    {'ticker': 'IKMP.JK', 'name': 'Indah Kiat Pulp & Paper', 'sector': 'Barang Baku'},
    {'ticker': 'IMJS.JK', 'name': 'Indomobil Multi Jasa', 'sector': 'Keuangan'},
    {'ticker': 'INAI.JK', 'name': 'Indal Aluminium Industry', 'sector': 'Barang Baku'},
    {'ticker': 'INCI.JK', 'name': 'Intanwijaya Internasional', 'sector': 'Barang Baku'},
    {'ticker': 'INDO.JK', 'name': 'Royal Investium Sekuritas', 'sector': 'Energi'},
    {'ticker': 'INDR.JK', 'name': 'Indorama Synthetics', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'INDS.JK', 'name': 'Indospring', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'INDX.JK', 'name': 'IDX Channel', 'sector': 'Keuangan'},
    {'ticker': 'INET.JK', 'name': 'Sinergi Inti Andalan Prima', 'sector': 'Infrastruktur'},
    {'ticker': 'INOV.JK', 'name': 'Inocycle Technology Group', 'sector': 'Barang Baku'},
    {'ticker': 'INPP.JK', 'name': 'Indonesian Paradise Property', 'sector': 'Properti & Real Estat'},
    {'ticker': 'INRU.JK', 'name': 'Toba Pulp Lestari', 'sector': 'Barang Baku'},
    {'ticker': 'INTD.JK', 'name': 'Inter Delta', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'IOTF.JK', 'name': 'Sumber Sinergi Makmur', 'sector': 'Teknologi'},
    {'ticker': 'IPOL.JK', 'name': 'Indopoly Swakarsa Industry', 'sector': 'Barang Baku'},
    {'ticker': 'IRRA.JK', 'name': 'Itama Ranoraya', 'sector': 'Kesehatan'},
    {'ticker': 'IRSX.JK', 'name': 'Asia Sejahtera Mina', 'sector': 'Teknologi'},
    {'ticker': 'ISEA.JK', 'name': 'Indo Oil Perkasa', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'ITIC.JK', 'name': 'Indonesian Tobacco', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'ITMA.JK', 'name': 'Sumber Energi Andalan', 'sector': 'Energi'},
    {'ticker': 'JAST.JK', 'name': 'Jasnita Telekomindo', 'sector': 'Infrastruktur'},
    {'ticker': 'JATI.JK', 'name': 'Informasi Teknologi Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'JAWA.JK', 'name': 'Jaya Agra Wattie', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'JAYA.JK', 'name': 'Armada Berjaya Trans', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'JECC.JK', 'name': 'Jembo Cable Company', 'sector': 'Perindustrian'},
    {'ticker': 'JIHD.JK', 'name': 'Jakarta International Hotels & Dev', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'JMAS.JK', 'name': 'Asuransi Jiwa Syariah Jasa Mitra Abadi', 'sector': 'Keuangan'},
    {'ticker': 'JSPT.JK', 'name': 'Jakarta Setiabudi Internasional', 'sector': 'Properti & Real Estat'},
    {'ticker': 'KAEF.JK', 'name': 'Kimia Farma', 'sector': 'Kesehatan'},
    {'ticker': 'KAQI.JK', 'name': 'Kaqi Indonesia', 'sector': 'Perindustrian'},
    {'ticker': 'KBLM.JK', 'name': 'Kabelindo Murni', 'sector': 'Perindustrian'},
    {'ticker': 'KBLV.JK', 'name': 'First Media', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'KDSI.JK', 'name': 'Kedawung Setia Industrial', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'KDTN.JK', 'name': 'Kedaton Makmur', 'sector': 'Properti & Real Estat'},
    {'ticker': 'KETR.JK', 'name': 'Semacom Integrated', 'sector': 'Perindustrian'},
    {'ticker': 'KICI.JK', 'name': 'Kedaung Indah Can', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'KINO.JK', 'name': 'Kino Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'KIOS.JK', 'name': 'Kioson Komersial Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'KJEN.JK', 'name': 'Krida Jaringan Nusantara', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'KLAS.JK', 'name': 'Klasik Distribusi Indonesia', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'KMDS.JK', 'name': 'Kurniamitra Duta Sentosa', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'KMTR.JK', 'name': 'Kirana Megatara', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'KOBX.JK', 'name': 'Kobexindo Tractors', 'sector': 'Perindustrian'},
    {'ticker': 'KOCI.JK', 'name': 'Kokoh Inti Arebama', 'sector': 'Perindustrian'},
    {'ticker': 'KOKA.JK', 'name': 'Koka Indonesia', 'sector': 'Infrastruktur'},
    {'ticker': 'KONI.JK', 'name': 'Perusahaan Bongkar Muat Kontermul', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'KOPI.JK', 'name': 'Fore Kopi Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'KRAS.JK', 'name': 'Krakatau Steel', 'sector': 'Barang Baku'},
    {'ticker': 'KRYA.JK', 'name': 'Bangun Karya Perkasa Jaya', 'sector': 'Infrastruktur'},
    {'ticker': 'KSIX.JK', 'name': 'Sinergi Multi Lestarindo', 'sector': 'Barang Baku'},
    {'ticker': 'KUAS.JK', 'name': 'Ace Oldfields', 'sector': 'Perindustrian'},
    {'ticker': 'LABA.JK', 'name': 'Ladangbaja Murni', 'sector': 'Perindustrian'},
    {'ticker': 'LABS.JK', 'name': 'Diagnos Laboratorium Utama', 'sector': 'Kesehatan'},
    {'ticker': 'LAJU.JK', 'name': 'Jasa Berdikari Logistics', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'LAPD.JK', 'name': 'Leyand International', 'sector': 'Energi'},
    {'ticker': 'LCKM.JK', 'name': 'LCK Global Utama', 'sector': 'Infrastruktur'},
    {'ticker': 'LEAD.JK', 'name': 'Logindo Samudramakmur', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'LIFE.JK', 'name': 'Asuransi Jiwa Sinarmas MSIG', 'sector': 'Keuangan'},
    {'ticker': 'LINK.JK', 'name': 'Link Net', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'LION.JK', 'name': 'Lion Metal Works', 'sector': 'Perindustrian'},
    {'ticker': 'LIVE.JK', 'name': 'Multimedika Internasional', 'sector': 'Kesehatan'},
    {'ticker': 'LMPI.JK', 'name': 'Langgeng Makmur Industri', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'LPCK.JK', 'name': 'Lippo Cikarang', 'sector': 'Properti & Real Estat'},
    {'ticker': 'LPGI.JK', 'name': 'Lippo General Insurance', 'sector': 'Keuangan'},
    {'ticker': 'LPIN.JK', 'name': 'Multi Prima Sejahtera', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'LPLI.JK', 'name': 'Star Pacific', 'sector': 'Teknologi'},
    {'ticker': 'LPPS.JK', 'name': 'Lippo Securities', 'sector': 'Keuangan'},
    {'ticker': 'LRNA.JK', 'name': 'Eka Sari Lorena Transport', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'LUCK.JK', 'name': 'Sentral Mitra Informatika', 'sector': 'Teknologi'},
    {'ticker': 'MAPB.JK', 'name': 'MAP Boga Adiperkasa', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'MASB.JK', 'name': 'Bank Multiarta Sentosa', 'sector': 'Keuangan'},
    {'ticker': 'MAXI.JK', 'name': 'Maxindo Karya Anugerah', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'MBAP.JK', 'name': 'Mitrabara Adiperdana', 'sector': 'Energi'},
    {'ticker': 'MBTO.JK', 'name': 'Martina Berto', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'MDKI.JK', 'name': 'Emdeki Utama', 'sector': 'Barang Baku'},
    {'ticker': 'MDLN.JK', 'name': 'Modernland Realty', 'sector': 'Properti & Real Estat'},
    {'ticker': 'MEDS.JK', 'name': 'Medikes Lab Indonesia', 'sector': 'Kesehatan'},
    {'ticker': 'MERI.JK', 'name': 'Merdeka Battery Materials', 'sector': 'Barang Baku'},
    {'ticker': 'MERK.JK', 'name': 'Merck', 'sector': 'Kesehatan'},
    {'ticker': 'MGNA.JK', 'name': 'Magna Investama Mandiri', 'sector': 'Keuangan'},
    {'ticker': 'MGRO.JK', 'name': 'Mahkota Group', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'MHKI.JK', 'name': 'Multi Hanna Kreasindo', 'sector': 'Perindustrian'},
    {'ticker': 'MICE.JK', 'name': 'Multi Indocitra', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'MINA.JK', 'name': 'Sanurhasta Mitra', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'MITI.JK', 'name': 'Mitrabahtera Segara Sejati', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'MKAP.JK', 'name': 'Multikarya Asia Pasifik', 'sector': 'Energi'},
    {'ticker': 'MKPI.JK', 'name': 'Metropolitan Kentjana', 'sector': 'Properti & Real Estat'},
    {'ticker': 'MLPT.JK', 'name': 'Multipolar Technology', 'sector': 'Teknologi'},
    {'ticker': 'MMIX.JK', 'name': 'Multi Medika Internasional', 'sector': 'Kesehatan'},
    {'ticker': 'MOLI.JK', 'name': 'Madusari Murni Indah', 'sector': 'Barang Baku'},
    {'ticker': 'MPIX.JK', 'name': 'Mitra Pack', 'sector': 'Perindustrian'},
    {'ticker': 'MPOW.JK', 'name': 'Megapower Makmur', 'sector': 'Infrastruktur'},
    {'ticker': 'MPRO.JK', 'name': 'Maha Properti Indonesia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'MPXL.JK', 'name': 'MPX Logistics International', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'MRAT.JK', 'name': 'Mustika Ratu', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'MSJA.JK', 'name': 'Majapahit Inti Corpora', 'sector': 'Keuangan'},
    {'ticker': 'MSKY.JK', 'name': 'MNC Sky Vision', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'MTWI.JK', 'name': 'Malacca Trust Wuwungan Insurance', 'sector': 'Keuangan'},
    {'ticker': 'MUTU.JK', 'name': 'Mutuagung Lestari', 'sector': 'Perindustrian'},
    {'ticker': 'MYOH.JK', 'name': 'Samindo Resources', 'sector': 'Energi'},
    {'ticker': 'NAIK.JK', 'name': 'Daaz Bara Lestari', 'sector': 'Perindustrian'},
    {'ticker': 'NASI.JK', 'name': 'Wahana Inti Makmur', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'NATO.JK', 'name': 'Nusantara Almazia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'NELY.JK', 'name': 'Pelayaran Nelly Dwi Putri', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'NEST.JK', 'name': 'Nature Nusantara', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'NETV.JK', 'name': 'Net Visi Media', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'NFCX.JK', 'name': 'NFC Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'NICE.JK', 'name': 'Adhi Kartiko Pratama', 'sector': 'Barang Baku'},
    {'ticker': 'NICK.JK', 'name': 'Charnic Capital', 'sector': 'Keuangan'},
    {'ticker': 'NICL.JK', 'name': 'PAM Mineral', 'sector': 'Barang Baku'},
    {'ticker': 'NIKL.JK', 'name': 'Pelat Timah Nusantara', 'sector': 'Barang Baku'},
    {'ticker': 'NIRO.JK', 'name': 'City Retail Developments', 'sector': 'Properti & Real Estat'},
    {'ticker': 'NOBU.JK', 'name': 'Bank Nationalnobu', 'sector': 'Keuangan'},
    {'ticker': 'NPGF.JK', 'name': 'Nindya Karya Persada', 'sector': 'Infrastruktur'},
    {'ticker': 'NRCA.JK', 'name': 'Nusa Raya Cipta', 'sector': 'Infrastruktur'},
    {'ticker': 'NSSS.JK', 'name': 'Nusantara Sawit Sejahtera', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'NTBK.JK', 'name': 'Bank Net Indonesia Syariah', 'sector': 'Keuangan'},
    {'ticker': 'NZIA.JK', 'name': 'Nusantara Almazia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'OASA.JK', 'name': 'Maharaksa Biru Energi', 'sector': 'Infrastruktur'},
    {'ticker': 'OBAT.JK', 'name': 'Prodia Widyahusada', 'sector': 'Kesehatan'},
    {'ticker': 'OBMD.JK', 'name': 'OBM Drilchem', 'sector': 'Barang Baku'},
    {'ticker': 'OILS.JK', 'name': 'Indo Oil Perkasa', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'OKAS.JK', 'name': 'Ancora Indonesia Resources', 'sector': 'Energi'},
    {'ticker': 'OPMS.JK', 'name': 'Optima Prima Metal Sinergi', 'sector': 'Perindustrian'},
    {'ticker': 'PADA.JK', 'name': 'Personel Alih Daya', 'sector': 'Perindustrian'},
    {'ticker': 'PADI.JK', 'name': 'Minna Padi Investama Sekuritas', 'sector': 'Keuangan'},
    {'ticker': 'PALM.JK', 'name': 'Provident Investasi Bersama', 'sector': 'Energi'},
    {'ticker': 'PAMG.JK', 'name': 'Bima Sakti Pertiwi', 'sector': 'Properti & Real Estat'},
    {'ticker': 'PART.JK', 'name': 'Pertamina Pratama', 'sector': 'Energi'},
    {'ticker': 'PBSA.JK', 'name': 'Paramita Bangun Sarana', 'sector': 'Infrastruktur'},
    {'ticker': 'PDES.JK', 'name': 'Destinasi Tirta Nusantara', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PDPP.JK', 'name': 'Primadaya Plastindo', 'sector': 'Barang Baku'},
    {'ticker': 'PEGE.JK', 'name': 'Panca Global Kapital', 'sector': 'Keuangan'},
    {'ticker': 'PEHA.JK', 'name': 'Phapros', 'sector': 'Kesehatan'},
    {'ticker': 'PEVE.JK', 'name': 'Panca Mitra Multiperdana', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'PGLI.JK', 'name': 'Pembangunan Graha Lestari Indah', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PGUN.JK', 'name': 'Pradiksi Gunatama', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'PICO.JK', 'name': 'Pelangi Indah Canindo', 'sector': 'Barang Baku'},
    {'ticker': 'PIPA.JK', 'name': 'Multi Spunindo Jaya', 'sector': 'Barang Baku'},
    {'ticker': 'PJAA.JK', 'name': 'Pembangunan Jaya Ancol', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PJHB.JK', 'name': 'Prima Jaya Habco', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'PKPK.JK', 'name': 'Perdana Karya Kebajikan', 'sector': 'Energi'},
    {'ticker': 'PMJS.JK', 'name': 'Putra Mandiri Jembar', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PMUI.JK', 'name': 'Prima Mulia Utama Indonesia', 'sector': 'Perindustrian'},
    {'ticker': 'PNBS.JK', 'name': 'Bank Panin Dubai Syariah', 'sector': 'Keuangan'},
    {'ticker': 'PNSE.JK', 'name': 'Pudjiadi & Sons', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'POLU.JK', 'name': 'Golden Flower', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PORT.JK', 'name': 'Nusantara Pelabuhan Handal', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'PPRE.JK', 'name': 'PP Presisi', 'sector': 'Infrastruktur'},
    {'ticker': 'PPRI.JK', 'name': 'Puradelta Lestari', 'sector': 'Properti & Real Estat'},
    {'ticker': 'PRAY.JK', 'name': 'Pelita Air Service', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'PRIM.JK', 'name': 'Royal Prima', 'sector': 'Kesehatan'},
    {'ticker': 'PSAB.JK', 'name': 'J Resources Asia Pasifik', 'sector': 'Barang Baku'},
    {'ticker': 'PSDN.JK', 'name': 'Prasidha Aneka Niaga', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'PSKT.JK', 'name': 'Red Planet Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PTIS.JK', 'name': 'Indo Straits', 'sector': 'Energi'},
    {'ticker': 'PTMP.JK', 'name': 'Mitra Pack', 'sector': 'Perindustrian'},
    {'ticker': 'PTPS.JK', 'name': 'Pulau Subsea', 'sector': 'Energi'},
    {'ticker': 'PTPW.JK', 'name': 'Pratama Widya', 'sector': 'Infrastruktur'},
    {'ticker': 'PTSN.JK', 'name': 'Sat Nusapersada', 'sector': 'Teknologi'},
    {'ticker': 'PTSP.JK', 'name': 'Pioneerindo Gourmet International', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'PUDP.JK', 'name': 'Pudjiadi Prestige', 'sector': 'Properti & Real Estat'},
    {'ticker': 'PURI.JK', 'name': 'Puri Global Sukses', 'sector': 'Properti & Real Estat'},
    {'ticker': 'PYFA.JK', 'name': 'Pyridam Farma', 'sector': 'Kesehatan'},
    {'ticker': 'PZZA.JK', 'name': 'Sarimelati Kencana', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'RANC.JK', 'name': 'Supra Boga Lestari', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'RATU.JK', 'name': 'Ratu Prabu Energi', 'sector': 'Energi'},
    {'ticker': 'RDTX.JK', 'name': 'Roda Vivatex', 'sector': 'Properti & Real Estat'},
    {'ticker': 'REAL.JK', 'name': 'Repower Asia Indonesia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'RELI.JK', 'name': 'Reliance Sekuritas Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'RGAS.JK', 'name': 'Kian Santang Muliatama', 'sector': 'Energi'},
    {'ticker': 'RIGS.JK', 'name': 'Rig Tenders Indonesia', 'sector': 'Energi'},
    {'ticker': 'RISE.JK', 'name': 'Jaya Sukses Makmur Sentosa', 'sector': 'Properti & Real Estat'},
    {'ticker': 'RLCO.JK', 'name': 'Relance Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'RMKO.JK', 'name': 'RMK Energy', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'ROCK.JK', 'name': 'Rock Fields Properti Indonesia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'ONY.JK', 'name': 'Rony Indonesia', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'ROTI.JK', 'name': 'Nippon Indosari Corpindo', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'RSCH.JK', 'name': 'Kedaton Makmur', 'sector': 'Perindustrian'},
    {'ticker': 'RUIS.JK', 'name': 'Radiant Utama Interinsco', 'sector': 'Energi'},
    {'ticker': 'SAFE.JK', 'name': 'Steady Safe', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'SAPX.JK', 'name': 'Satria Antaran Prima', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'SATU.JK', 'name': 'Kota Satu Properti', 'sector': 'Properti & Real Estat'},
    {'ticker': 'SBMA.JK', 'name': 'Surya Biru Madani', 'sector': 'Barang Baku'},
    {'ticker': 'SCCO.JK', 'name': 'Supreme Cable Manufacturing', 'sector': 'Perindustrian'},
    {'ticker': 'SCNP.JK', 'name': 'Selaras Citra Nusantara Perkasa', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SDMU.JK', 'name': 'Sidomulyo Selaras', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'SDPC.JK', 'name': 'Millennium Pharmacon International', 'sector': 'Kesehatan'},
    {'ticker': 'SDRA.JK', 'name': 'Bank Woori Saudara Indonesia 1906', 'sector': 'Keuangan'},
    {'ticker': 'SEMA.JK', 'name': 'Semacom Integrated', 'sector': 'Perindustrian'},
    {'ticker': 'SFAN.JK', 'name': 'Sinar Eka Selaras', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SHID.JK', 'name': 'Hotel Sahid Jaya International', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SICO.JK', 'name': 'Sigma Energy Compressindo', 'sector': 'Energi'},
    {'ticker': 'SKBM.JK', 'name': 'Sekar Bumi', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'SKLT.JK', 'name': 'Sekar Laut', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'SLIS.JK', 'name': 'Gaya Abadi Sempurna', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SMDM.JK', 'name': 'Suryamas Dutamakmur', 'sector': 'Properti & Real Estat'},
    {'ticker': 'SMGA.JK', 'name': 'Sumber Mineral Global Abadi', 'sector': 'Energi'},
    {'ticker': 'SMKL.JK', 'name': 'Satyamitra Kemas Lestari', 'sector': 'Barang Baku'},
    {'ticker': 'SMLE.JK', 'name': 'Samudera Luas Paramacitra', 'sector': 'Perindustrian'},
    {'ticker': 'SMMT.JK', 'name': 'Golden Eagle Energy', 'sector': 'Energi'},
    {'ticker': 'SNLK.JK', 'name': 'Sunter Lakeside Hotel', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SOCI.JK', 'name': 'Soechi Lines', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'SOHO.JK', 'name': 'Soho Global Health', 'sector': 'Kesehatan'},
    {'ticker': 'SOLA.JK', 'name': 'MidPlaza Prima', 'sector': 'Properti & Real Estat'},
    {'ticker': 'SONA.JK', 'name': 'Sona Topas Tourism Foundation', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'SOTS.JK', 'name': 'Satria Mega Investama', 'sector': 'Keuangan'},
    {'ticker': 'SPMA.JK', 'name': 'Suparma', 'sector': 'Barang Baku'},
    {'ticker': 'SRAJ.JK', 'name': 'Sejahteraraya Indonesia', 'sector': 'Kesehatan'},
    {'ticker': 'SRSN.JK', 'name': 'Indo Acidatama', 'sector': 'Barang Baku'},
    {'ticker': 'SSTM.JK', 'name': 'Sunson Textile Manufacturer', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'STRK.JK', 'name': 'Shark Mind Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'STTP.JK', 'name': 'Siantar Top', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'SULI.JK', 'name': 'SLJ Global', 'sector': 'Barang Baku'},
    {'ticker': 'SUPA.JK', 'name': 'Sunindo Pratama', 'sector': 'Energi'},
    {'ticker': 'SURE.JK', 'name': 'Strategi Inti Prima', 'sector': 'Keuangan'},
    {'ticker': 'SURI.JK', 'name': 'Murni Sadar', 'sector': 'Kesehatan'},
    {'ticker': 'SWID.JK', 'name': 'Saraswanti Indoland Development', 'sector': 'Properti & Real Estat'},
    {'ticker': 'TALF.JK', 'name': 'Tunas Alfin', 'sector': 'Barang Baku'},
    {'ticker': 'TAYS.JK', 'name': 'Jaya Swarasa Agung', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'TBMS.JK', 'name': 'Tembaga Mulia Semanan', 'sector': 'Barang Baku'},
    {'ticker': 'TCID.JK', 'name': 'Mandom Indonesia', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'TCPI.JK', 'name': 'Transcoal Pacific', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'TFAS.JK', 'name': 'Telefast Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'TGKA.JK', 'name': 'Tigaraksa Satria', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'TIFA.JK', 'name': 'KDB Tifa Finance', 'sector': 'Keuangan'},
    {'ticker': 'TIRA.JK', 'name': 'Tira Austenite', 'sector': 'Perindustrian'},
    {'ticker': 'TLDN.JK', 'name': 'Teladan Prima Agro', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'TMPO.JK', 'name': 'Tempo Intimedia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'TNCA.JK', 'name': 'Trimuda Nuansa Citra', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'TOOL.JK', 'name': 'Logistik Tool Indonesia', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'TOSK.JK', 'name': 'Toska Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'TOTO.JK', 'name': 'Surya Toto Indonesia', 'sector': 'Barang Baku'},
    {'ticker': 'TPIA.JK', 'name': 'Chandra Asri Pacific', 'sector': 'Barang Baku'},
    {'ticker': 'TRIN.JK', 'name': 'Perintis Triniti Properti', 'sector': 'Properti & Real Estat'},
    {'ticker': 'TRIS.JK', 'name': 'Trisula International', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'TRJA.JK', 'name': 'Transkon Jaya', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'TRON.JK', 'name': 'Techno9 Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'TRST.JK', 'name': 'Trias Sentosa', 'sector': 'Barang Baku'},
    {'ticker': 'TRUE.JK', 'name': 'Trinitan Metals and Minerals', 'sector': 'Barang Baku'},
    {'ticker': 'TRUK.JK', 'name': 'Guna Timur Raya', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'TRUS.JK', 'name': 'Trust Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'TYRE.JK', 'name': 'King Tire Indonesia', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'UANG.JK', 'name': 'Centratama Telekomunikasi', 'sector': 'Keuangan'},
    {'ticker': 'UFOE.JK', 'name': 'Damai Sejahtera Abadi', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'UNTD.JK', 'name': 'United Family Food', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'URBN.JK', 'name': 'Urban Jakarta Propertindo', 'sector': 'Properti & Real Estat'},
    {'ticker': 'UVCR.JK', 'name': 'Trimegah Karya Pratama', 'sector': 'Teknologi'},
    {'ticker': 'VAST.JK', 'name': 'Vastland Indonesia', 'sector': 'Properti & Real Estat'},
    {'ticker': 'VERN.JK', 'name': 'Verena Multi Finance', 'sector': 'Keuangan'},
    {'ticker': 'VINS.JK', 'name': 'Victoria Insurance', 'sector': 'Keuangan'},
    {'ticker': 'VISI.JK', 'name': 'Visicorp Indonesia', 'sector': 'Teknologi'},
    {'ticker': 'VKTR.JK', 'name': 'VKTR Teknologi Mobilitas', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'VOKS.JK', 'name': 'Voksel Electric', 'sector': 'Perindustrian'},
    {'ticker': 'VRNA.JK', 'name': 'Verena Multi Finance', 'sector': 'Keuangan'},
    {'ticker': 'VTNY.JK', 'name': 'Venteny Fortuna International', 'sector': 'Teknologi'},
    {'ticker': 'WAPO.JK', 'name': 'Wahana Pronatural', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'WEGE.JK', 'name': 'Wijaya Karya Bangunan Gedung', 'sector': 'Infrastruktur'},
    {'ticker': 'WEHA.JK', 'name': 'Weha Transportasi Indonesia', 'sector': 'Transportasi & Logistik'},
    {'ticker': 'WIFI.JK', 'name': 'Solusi Sinergi Digital', 'sector': 'Infrastruktur'},
    {'ticker': 'WINE.JK', 'name': 'Hatten Bali', 'sector': 'Barang Konsumsi Primer'},
    {'ticker': 'WIRG.JK', 'name': 'WIR ASIA', 'sector': 'Teknologi'},
    {'ticker': 'WOMF.JK', 'name': 'Wahana Ottomitra Multiartha', 'sector': 'Keuangan'},
    {'ticker': 'WOWS.JK', 'name': 'Ginting Jaya Energi', 'sector': 'Energi'},
    {'ticker': 'YELO.JK', 'name': 'Yelooo Integra Datanet', 'sector': 'Teknologi'},
    {'ticker': 'YOII.JK', 'name': 'Yanaprima Hastapersada', 'sector': 'Barang Baku'},
    {'ticker': 'YPAS.JK', 'name': 'Yanaprima Hastapersada', 'sector': 'Barang Baku'},
    {'ticker': 'YULE.JK', 'name': 'Yulie Sekuritas Indonesia', 'sector': 'Keuangan'},
    {'ticker': 'ZATA.JK', 'name': 'Bersama Zatta Jaya', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ZONE.JK', 'name': 'Mega Perintis', 'sector': 'Barang Konsumsi Sekunder'},
    {'ticker': 'ZYRX.JK', 'name': 'Zyrexindo Mandiri Buana', 'sector': 'Teknologi'},
]

DBX_TICKER_SYMBOLS: list[str] = [t["ticker"] for t in DBX_TICKERS]
DBX_TICKER_META: dict[str, dict] = {t["ticker"]: t for t in DBX_TICKERS}
